---
extends: default

rules:
  line-length:
    max: 120
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false
